Repository goOHDARS/goDarsTest, pull requests merged in 2024-06, with the labels that each got.

#27 Add Course Querying Redux
  src/actions/courses.ts
  src/reducers/courses.ts
Labels: chore

#28 Feature/onboarding
  .eslintrc.js
  .github/workflows/lint.yml
  .prettierrc
  README.md
  app.json
  package-lock.json
  package.json
  src/actions/courses.ts
  src/actions/user.ts
  src/authenticated/MainPage.tsx
  src/authenticated/Onboarding.tsx
  src/components/BottomTabBar.tsx
  src/components/Divider.tsx
  src/components/PasswordRequirements.tsx
  src/components/ScreenLayout.tsx
  src/components/SelectedCourses.tsx
  src/components/Semester.tsx
  src/components/Snackbar.tsx
  src/reducers/courses.ts
  src/reducers/majors.ts
  src/reducers/user.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
  src/unauthenticated/LandingScreen.tsx
  src/unauthenticated/SignUpScreen.tsx
  src/unauthenticated/index.tsx
Labels: frontend, feature

#32 Assistant Tab
  .eslintrc.js
  package-lock.json
  package.json
  src/actions/conversations.ts
  src/authenticated/Assistant.tsx
  src/authenticated/MainPage.tsx
  src/authenticated/index.tsx
  src/components/BottomTabBar.tsx
  src/components/ChatScreen/index.tsx
  src/components/ChatScreen/styles.ts
  src/components/ChatScreen/useViewModel.ts
  src/components/ScreenLayout.tsx
  src/components/Semester.tsx
  src/reducers/conversations.ts
  src/reducers/index.ts
Labels: feature, fullstack

#33 Fix Keyboard Avoiding View on IOS
  src/components/BottomTabBar.tsx
  src/components/ChatScreen/index.tsx
  src/components/ChatScreen/useViewModel.ts
  src/components/ScreenLayout.tsx
Labels: bug
