Repository goOHDARS/goDarsTest, pull requests merged in 2024-09, with the labels that each got.

#35 Compute Current Semester
  package-lock.json
  package.json
  src/actions/user.ts
  src/authenticated/Onboarding.tsx
  src/reducers/user.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
Labels: chore, fullstack

#36 Fix Course Loading Errors
  src/actions/user.ts
  src/authenticated/MainPage.tsx
  src/authenticated/Onboarding.tsx
  src/components/Semester.tsx
  src/hooks/useHandleAuthState.ts
  src/reducers/conversations.ts
  src/reducers/courses.ts
  src/reducers/majors.ts
  src/reducers/user.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
Labels: bug

#38 Redesign Auth
  src/Root.tsx
  src/actions/api.ts
  src/actions/user.ts
  src/authenticated/index.tsx
  src/hooks/useHandleAuthState.ts
  src/hooks/useInitialDataLoader.ts
  src/reducers/user.ts
  src/unauthenticated/LandingScreen.tsx
  src/unauthenticated/SignInScreen.tsx
  src/unauthenticated/SignUpScreen.tsx
  src/unauthenticated/index.tsx
  src/utils/storage.ts
  tsconfig.json
Labels: frontend, chore

#39 Fix Onboarding Querying
  src/actions/courses.ts
  src/authenticated/Onboarding.tsx
  src/authenticated/Onboarding/SelectedCourses.tsx
  src/authenticated/Onboarding/index.tsx
  src/authenticated/Onboarding/styles.ts
  src/authenticated/Onboarding/useViewModel.ts
Labels: bug, frontend

#42 Hide Tabbar when not onboarded
  src/components/BottomTabBar.tsx
Labels: bug

#40 Profile Functionality && Update User
  .gitignore
  assets/image.png
  babel.config.js
  package-lock.json
  package.json
  src/actions/user.ts
  src/authenticated/Dashboard/Bricks/index.tsx
  src/authenticated/Dashboard/Bricks/styles.ts
  src/authenticated/Dashboard/Profile/ColorCustomizer.tsx
  src/authenticated/Dashboard/Profile/ProfileCustomizer.tsx
  src/authenticated/Dashboard/Profile/index.tsx
  src/authenticated/Dashboard/Profile/styles.ts
  src/authenticated/Dashboard/WhatIfDARS/index.tsx
  src/authenticated/Dashboard/WhatIfDARS/styles.ts
  src/authenticated/Dashboard/index.tsx
  src/authenticated/MainPage.tsx
  src/authenticated/Onboarding/CourseOverview.tsx
  src/authenticated/Onboarding/SelectedCourses.tsx
  src/authenticated/Onboarding/index.tsx
  src/authenticated/Onboarding/useViewModel.ts
  src/components/ScreenLayout.tsx
  src/components/Semester.tsx
  src/components/Semesters/index.tsx
  src/components/Semesters/styles.ts
  src/components/Snackbar.tsx
  src/components/UserProfile.tsx
  src/reducers/courses.ts
  src/reducers/user.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
  src/unauthenticated/SignInScreen.tsx
  src/unauthenticated/SignUpScreen.tsx
Labels: feature, chore, fullstack

#43 Organize authenticated file structure
  src/authenticated/features/ChatScreen/index.tsx
  src/authenticated/features/ChatScreen/styles.ts
  src/authenticated/features/ChatScreen/useViewModel.ts
  src/authenticated/features/Dashboard/Bricks/index.tsx
  src/authenticated/features/Dashboard/Bricks/styles.ts
  src/authenticated/features/Dashboard/Profile/ColorCustomizer.tsx
  src/authenticated/features/Dashboard/Profile/ProfileCustomizer.tsx
  src/authenticated/features/Dashboard/Profile/index.tsx
  src/authenticated/features/Dashboard/Profile/styles.ts
  src/authenticated/features/Dashboard/WhatIfDARS/index.tsx
  src/authenticated/features/Dashboard/WhatIfDARS/styles.ts
  src/authenticated/features/Dashboard/index.tsx
  src/authenticated/features/Onboarding/CourseOverview.tsx
  src/authenticated/features/Onboarding/SelectedCourses.tsx
  src/authenticated/features/Onboarding/index.tsx
  src/authenticated/features/Onboarding/styles.ts
  src/authenticated/features/Onboarding/useViewModel.ts
  src/authenticated/index.tsx
  src/authenticated/pages/Assistant.tsx
  src/authenticated/pages/CourseSelect.tsx
  src/authenticated/pages/MainPage.tsx
  src/authenticated/pages/Overview.tsx
Labels: chore
