Repository goOHDARS/goDarsTest, pull requests merged in 2024-05, with the labels that each got.

#12 Update Expo
  package-lock.json
  package.json
Labels: bug, frontend

#14 Automate linting
  .eslintrc.js
  .github/workflows/lint.yml
  .husky/pre-commit
  babel.config.js
  package-lock.json
  package.json
  src/actions/api.ts
  src/actions/user.ts
  src/components/BottomTabBar.tsx
  src/hooks/store.ts
  src/hooks/useHandleAuthState.ts
  src/reducers/majors.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
Labels: frontend, feature

#18 Add rule to never allow semis
  .eslintrc.js
Labels: chore, fullstack

#22 Fix Redux types
  src/actions/api.ts
  src/actions/user.ts
  src/reducers/majors.ts
  src/reducers/user.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
Labels: bug, frontend

#23 Feat add pid sticky && Reflect back-end changes
  Makefile
  src/unauthenticated/AdditionalInfoScreen.tsx
  src/unauthenticated/SignUpScreen.tsx
Labels: feature, chore, fullstack

#24 Courses Redux State
  src/actions/courses.ts
  src/reducers/courses.ts
  src/reducers/index.ts
  src/reducers/majors.ts
  src/reducers/user.ts
Labels: feature, fullstack

#26 Feat add main page
  .prettierrc
  src/authenticated/MainPage.tsx
  src/components/Divider.tsx
  src/components/Semester.tsx
  src/reducers/courses.ts
  src/reducers/user.ts
  src/unauthenticated/AdditionalInfoScreen.tsx
Labels: frontend, feature, fullstack
